apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubernator-web
  namespace: kubernator
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernator-web
