apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernator-web-auth
  namespace: kubernator
  labels:
    app.kubernetes.io/name: kubernator-web
    app.kubernetes.io/part-of: kubernator
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 64Mi
